[package]
name = "invectedgamelogic"
version = "0.1.0"
authors = []

[lib]
name = "invectedgamelogic"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.16.0"
rustler_codegen = "0.16.0"
lazy_static = "0.2"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
